target-version = "py312"

# [per-file-ignores]
# "__init__.py" = ["F403", "F405"]

[lint]
ignore-init-module-imports = true
select = ["ALL"]
ignore = [
    "D100", "D101", "D102", "D103",
    "D104", "D105", "D106", "D107"
]
